### ISSUE TITLE
Project management basics

### ISSUE THREAD

**Issue by csta01** [Ensign-College/survival-guide#14]
- [x] Complete Flutter [build documentation](https://github.com/Ensign-College/survival-guide/wiki)
- [x] Start survival-guide CI/CD
- [x] Link Discord with survival-guide

**Comment by DereckAn** [comment]
@moronizacmel  Hey, I will be working on CI/CD part of it so you can offload some of your work

**Comment by DereckAn** [comment]
@moronizacmel  Just linked Github with Discord too

**Comment by csta01** [comment]
@moronizacmel  Looks like Discord needs to be set up correctly. I will ask @MiriamJB  to link it correctly. Thank you!

**Comment by sapoepsilon** [comment]
@DereckAn @moronizacmel, I think we have done pretty solid work here. And could mark this issue as done

**Comment by sapoepsilon** [comment]
Closing per:  commit 12f87d5
